version: '3.7'
services:

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app
    command: composer install

  php:
    build: ./container-build/php
    ports:
      - "9000:9000"
    command: php -S 0.0.0.0:9000 -t public/
    volumes:
      - .:/var/www
